name: allthenamesaretaken
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfd7da'
    - '#999a9c'
    - '#030a10'
    - '#4f687c'
    - '#31475e'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
