name: allthenamesaretaken
favicon: null
layout_spectrum: 0.6179606867954135
typography_spectrum: 0.9094963730312884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.18919686344452202
  lightness: 0.39054611953906715
  saturation: 0.27043922361917794
  rhythmicContrast: 0.7040298718493432
purpose: []
